/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DataBase.Sql;
import DataBase.Tables.CaseHistory;
import DataBase.Tables.Cases;
import Layout.WrapLayout;
import View.Elements.Pnl_CaseElement;
import View.Elements.Pnl_CaseHistoryElement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Dlg_SearchComplain extends javax.swing.JDialog {

    /**
     * Creates new form Dlg_SearchComplain
     */
    public Dlg_SearchComplain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public boolean show = false;
    Long Caseid;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Select = new javax.swing.JButton();
        Btn_Search = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        DskPn_CaseHistory = new javax.swing.JDesktopPane();
        jLabel27 = new javax.swing.JLabel();
        Chk_BxCaseType = new javax.swing.JCheckBox();
        Txt_Number = new javax.swing.JTextField();
        CmbBx_CaseType = new javax.swing.JComboBox();
        ChckBx_Phone = new javax.swing.JCheckBox();
        DtPck_StartDt = new org.jdesktop.swingx.JXDatePicker();
        jLabel28 = new javax.swing.JLabel();
        ChkBx_Date = new javax.swing.JCheckBox();
        DtPck_EndDt = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pnl_CaseList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Btn_Select.setText("Select Current Case");
        Btn_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SelectActionPerformed(evt);
            }
        });

        Btn_Search.setText("Search");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Search Parameters");

        jScrollPane6.setViewportView(DskPn_CaseHistory);
        DskPn_CaseHistory.setLayout(new WrapLayout());

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("Start");

        Chk_BxCaseType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Chk_BxCaseType.setText("Case Type");

        Txt_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NumberActionPerformed(evt);
            }
        });

        CmbBx_CaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Category" }));
        CmbBx_CaseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBx_CaseTypeActionPerformed(evt);
            }
        });

        ChckBx_Phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ChckBx_Phone.setText("Phone");

        DtPck_StartDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtPck_StartDtActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("End");

        ChkBx_Date.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ChkBx_Date.setText("Date");

        DtPck_EndDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtPck_EndDtActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout Pnl_CaseListLayout = new javax.swing.GroupLayout(Pnl_CaseList);
        Pnl_CaseList.setLayout(Pnl_CaseListLayout);
        Pnl_CaseListLayout.setHorizontalGroup(
            Pnl_CaseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        Pnl_CaseListLayout.setVerticalGroup(
            Pnl_CaseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Pnl_CaseList);
        Pnl_CaseList.setLayout(new WrapLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Btn_Search))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChckBx_Phone)
                                    .addComponent(ChkBx_Date))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DtPck_EndDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Txt_Number, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DtPck_StartDt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Chk_BxCaseType)
                                .addGap(12, 12, 12)
                                .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChckBx_Phone)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ChkBx_Date)
                                    .addComponent(DtPck_StartDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)))
                            .addComponent(Txt_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DtPck_EndDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chk_BxCaseType)
                            .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(Btn_Search)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Select)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NumberActionPerformed
        // TODO add your handling code here:
        if(Txt_Number.getText().length()>0){
        ChckBx_Phone.setSelected(true);
        }else{
        ChckBx_Phone.setSelected(false);
        }
    }//GEN-LAST:event_Txt_NumberActionPerformed

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        // TODO add your handling code here:
        String Query = " Select Distinct(CaseID) from Consolidate where 1=1";
        System.out.println("query in search "+Query);
        if(ChckBx_Phone.isSelected()){
        Query += " AND CallNumber="+Txt_Number.getText();
        }
        if(ChkBx_Date.isSelected()){
        Date sdt = DtPck_StartDt.getDate();
        Date edt = DtPck_EndDt.getDate();
        if(sdt!=null){
        Query += " AND DateStamp >="+Global.JavaDateToMysql(sdt)+"\"" ;
        }else{
        infoBox("Please Specify Start date or Uncheck date criteria", "Delhi Women Cell");
        }
        if(edt!=null){
        Query += " AND DateStamp <= \""+Global.JavaDateToMysql(edt)+"\"" ;
        }else{
          infoBox("Please Specify End date or Uncheck date criteria", "Delhi Women Cell");
        }
                
        }
        if(Chk_BxCaseType.isSelected()){
        Query +=" AND CaseType='"+CmbBx_CaseType.getSelectedItem().toString()+"'";
        }
                        String caselist = "(";
        try {
            Sql sql = new Sql();
            ResultSet rs = sql.ExecuteQuery(Query);
            while (rs.next()) {
                if (caselist.length() > 2) {
                    caselist += ", '" + rs.getString(1) + "'";
                } else {
                    caselist += "'" + rs.getString(1) + "'";
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        caselist += ")";
        if (caselist.length() > 3) {
            ArrayList<Cases> cases = new Cases().loadclass(" idCase IN " + caselist);
            for (Cases ob : cases) {
                System.out.println("Adding Cases");
                Pnl_CaseElement obj = new Pnl_CaseElement();
                obj.LoadElement(ob);
                final String id = obj.id;
                obj.getBtn_Select().removeActionListener(obj.getBtn_Select().getActionListeners()[0]);
                obj.getBtn_Select().addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Caseid = Long.valueOf(id);
                        ArrayList<CaseHistory> caseHistory = new CaseHistory().loadclass(" CaseID =" + Caseid + " order by DateStamp DESC");
                        DskPn_CaseHistory.removeAll();
                        for (CaseHistory ch : caseHistory) {
                            final String CaseHID = String.valueOf(ch.getId());
                            Pnl_CaseHistoryElement obj = new Pnl_CaseHistoryElement();
                            obj.LoadElement(ch);

                            DskPn_CaseHistory.add(obj);
                            DskPn_CaseHistory.revalidate();
                            DskPn_CaseHistory.repaint();
                        }
                        
                    }
                });
                Pnl_CaseList.add(obj);
                Pnl_CaseList.revalidate();
                Pnl_CaseList.repaint();
                this.repaint();
                System.out.println("Adding case element");
            }
    }
    }//GEN-LAST:event_Btn_SearchActionPerformed
public static void infoBox(String infoMessage, String location) {
        JOptionPane.showMessageDialog(null, infoMessage, location, JOptionPane.ERROR_MESSAGE);
    }
    private void DtPck_StartDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtPck_StartDtActionPerformed
        // TODO add your handling code here:
       
        ChkBx_Date.setSelected(true);
       
    }//GEN-LAST:event_DtPck_StartDtActionPerformed

    private void DtPck_EndDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtPck_EndDtActionPerformed
        // TODO add your handling code here:
       
        ChkBx_Date.setSelected(true);
       
    }//GEN-LAST:event_DtPck_EndDtActionPerformed

    private void CmbBx_CaseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBx_CaseTypeActionPerformed
        // TODO add your handling code here:
        if(!CmbBx_CaseType.getSelectedItem().toString().equals("Select a Category")){
        Chk_BxCaseType.setSelected(true);
        }else{
        Chk_BxCaseType.setSelected(false);
        }
    }//GEN-LAST:event_CmbBx_CaseTypeActionPerformed

    private void Btn_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SelectActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_Btn_SelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_SearchComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_SearchComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_SearchComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_SearchComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_SearchComplain dialog = new Dlg_SearchComplain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Search;
    private javax.swing.JButton Btn_Select;
    private javax.swing.JCheckBox ChckBx_Phone;
    private javax.swing.JCheckBox ChkBx_Date;
    private javax.swing.JCheckBox Chk_BxCaseType;
    private javax.swing.JComboBox CmbBx_CaseType;
    private javax.swing.JDesktopPane DskPn_CaseHistory;
    private org.jdesktop.swingx.JXDatePicker DtPck_EndDt;
    private org.jdesktop.swingx.JXDatePicker DtPck_StartDt;
    private javax.swing.JPanel Pnl_CaseList;
    private javax.swing.JTextField Txt_Number;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
