/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DataBase.OutBound;
import DataBase.Sql;
import DataBase.Tables.Accused;
import DataBase.Tables.Agent;
import DataBase.Tables.Caller;
import DataBase.Tables.Calls;
import DataBase.Tables.CaseHistory;
import DataBase.Tables.Cases;
import Layout.WrapLayout;
import View.Elements.Pnl_CallerElement;
import View.Elements.Pnl_CaseElement;
import View.Elements.Pnl_CaseHistoryElement;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author admin
 */
public class Screen_CaseReports extends javax.swing.JFrame {

    /**
     * Creates new form Screen_CaseReports
     */
    public Screen_CaseReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Pnl_CaseList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pnl_CaseHistory = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pnl_Caller = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pnl_Accused = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SrchFld_CmpltNo = new org.jdesktop.swingx.JXSearchField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        CmbBx_CaseType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        DtPck_Case = new org.jdesktop.swingx.JXDatePicker();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Pnl_CaseDirctry = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        Pnl_RecrdDirctry = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        TxtDialScreen = new javax.swing.JTextField();
        Btn_Dial = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Btn_Search = new javax.swing.JButton();
        Btn_More = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Pnl_CaseListLayout = new javax.swing.GroupLayout(Pnl_CaseList);
        Pnl_CaseList.setLayout(Pnl_CaseListLayout);
        Pnl_CaseListLayout.setHorizontalGroup(
            Pnl_CaseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        Pnl_CaseListLayout.setVerticalGroup(
            Pnl_CaseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Pnl_CaseList);
        Pnl_CaseList.setLayout(new WrapLayout());

        javax.swing.GroupLayout Pnl_CaseHistoryLayout = new javax.swing.GroupLayout(Pnl_CaseHistory);
        Pnl_CaseHistory.setLayout(Pnl_CaseHistoryLayout);
        Pnl_CaseHistoryLayout.setHorizontalGroup(
            Pnl_CaseHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        Pnl_CaseHistoryLayout.setVerticalGroup(
            Pnl_CaseHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        Pnl_CaseHistory.setLayout(new WrapLayout());

        jScrollPane2.setViewportView(Pnl_CaseHistory);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Case List");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Case History");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Pnl_Caller.setBorder(javax.swing.BorderFactory.createTitledBorder("Caller Info"));

        javax.swing.GroupLayout Pnl_CallerLayout = new javax.swing.GroupLayout(Pnl_Caller);
        Pnl_Caller.setLayout(Pnl_CallerLayout);
        Pnl_CallerLayout.setHorizontalGroup(
            Pnl_CallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        Pnl_CallerLayout.setVerticalGroup(
            Pnl_CallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(Pnl_Caller);

        Pnl_Accused.setBorder(javax.swing.BorderFactory.createTitledBorder("Accused Info"));

        javax.swing.GroupLayout Pnl_AccusedLayout = new javax.swing.GroupLayout(Pnl_Accused);
        Pnl_Accused.setLayout(Pnl_AccusedLayout);
        Pnl_AccusedLayout.setHorizontalGroup(
            Pnl_AccusedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        Pnl_AccusedLayout.setVerticalGroup(
            Pnl_AccusedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(Pnl_Accused);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Case Info");

        jXLabel1.setText("Complaint No.");

        CmbBx_CaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Others", "Abduction", "Acid_Attack", "Callback_from_100", "Child_Sexual_Abuse (POSCO)", "Dangerous_Attack", "Domestic_Violence", "Dowry_Death", "Dowry_Violence", "Illegal_Confinement", "Incoming_obscene", "Kidnaping", "Life_Threatening_attack_by_Family", "Missing", "Murder", "Obscene_Call", "Petty_Quarrel", "Property_cases", "Rape", "Sexual_Abuse", "Stalking", "Threat_To_Life", "Violence_by_Khap_Biradari_Panchayat" }));

        jLabel6.setText("Case Type");

        jXLabel2.setText("Case Date");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_CaseDirctry.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Pnl_CaseDirctryLayout = new javax.swing.GroupLayout(Pnl_CaseDirctry);
        Pnl_CaseDirctry.setLayout(Pnl_CaseDirctryLayout);
        Pnl_CaseDirctryLayout.setHorizontalGroup(
            Pnl_CaseDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        Pnl_CaseDirctryLayout.setVerticalGroup(
            Pnl_CaseDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jScrollPane11.setViewportView(Pnl_CaseDirctry);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 501, 100));

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        Pnl_RecrdDirctry.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_RecrdDirctry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout Pnl_RecrdDirctryLayout = new javax.swing.GroupLayout(Pnl_RecrdDirctry);
        Pnl_RecrdDirctry.setLayout(Pnl_RecrdDirctryLayout);
        Pnl_RecrdDirctryLayout.setHorizontalGroup(
            Pnl_RecrdDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
        );
        Pnl_RecrdDirctryLayout.setVerticalGroup(
            Pnl_RecrdDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jScrollPane12.setViewportView(Pnl_RecrdDirctry);
        Pnl_RecrdDirctry.setLayout(new WrapLayout());

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 490, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));

        TxtDialScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDialScreenActionPerformed(evt);
            }
        });

        Btn_Dial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Dial.png"))); // NOI18N
        Btn_Dial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DialActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("1");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setIconTextGap(0);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4DialKeyPad(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("4");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(0);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5DialKeyPad(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("7");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(0);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6DialKeyPad(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("2");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(0);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7DialKeyPad(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("5");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setIconTextGap(0);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8DialKeyPad(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("8");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setIconTextGap(0);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9DialKeyPad(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton13.setText("3");
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setIconTextGap(0);
        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13DialKeyPad(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton14.setText("9");
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setIconTextGap(0);
        jButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14DialKeyPad(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton15.setText("6");
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setIconTextGap(0);
        jButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15DialKeyPad(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton16.setText("*");
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setIconTextGap(0);
        jButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16DialKeyPad(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton17.setText("#");
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setIconTextGap(0);
        jButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17DialKeyPad(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton18.setText("0");
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setIconTextGap(0);
        jButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18DialKeyPad(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btn_Dial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDialScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDialScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Dial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 200, 140));

        Btn_Search.setText("Search");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        Btn_More.setText("More>>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SrchFld_CmpltNo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DtPck_Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Btn_Search)
                .addGap(61, 61, 61)
                .addComponent(Btn_More)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel3)
                        .addGap(252, 252, 252)
                        .addComponent(jLabel5)
                        .addGap(435, 435, 435)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SrchFld_CmpltNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(DtPck_Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Search)
                    .addComponent(Btn_More))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDialScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDialScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDialScreenActionPerformed

    private void Btn_DialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DialActionPerformed
        // TODO add your handling code here:
        if (Caseid == null) {
            infoBox("Please select a Case before you proceed", "Delhi Women Cell");
            return;
        }
        if (Caseid > 0) {
            try {
                Cases cs = new Cases().loadclass(" idCase=" + Caseid).get(0);
                String CaseName = cs.getReadableName();
                infoBox("You are going to work on case : " + CaseName, "Delhi Women Cell");
            } catch (Exception e) {
                infoBox("Please select a Case before you proceed", "Delhi Women Cell");
                return;
            }
        }
        OutBound ob = new OutBound();
        ob.connect(TxtDialScreen.getText());
        infoBox("Your Call Request is submitted. Please wait for 1 minute for server to connect you.", "Delhi WomenCell");
        Pnl_CaseHistoryElement pce = new Pnl_CaseHistoryElement();
        pce.AudioPanel.disable();
        pce.getBtn_Save().setEnabled(true);
        pce.getTxt_Note().setEnabled(true);
        pce.Agentid = Long.valueOf(Global.AgentPK);
        pce.Caseid = Caseid;
        JDialog caseentry = new JDialog();
        caseentry.add(pce);
        caseentry.setSize(caseentry.getPreferredSize());
        caseentry.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        caseentry.show();
    }//GEN-LAST:event_Btn_DialActionPerformed
    public static void infoBox(String infoMessage, String location) {
        JOptionPane.showMessageDialog(null, infoMessage, location, JOptionPane.ERROR_MESSAGE);
    }
    private void jButton4DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton4DialKeyPad

    private void jButton5DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton5DialKeyPad

    private void jButton6DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton6DialKeyPad

    private void jButton7DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton7DialKeyPad

    private void jButton8DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton8DialKeyPad

    private void jButton9DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton9DialKeyPad

    private void jButton13DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton13DialKeyPad

    private void jButton14DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton14DialKeyPad

    private void jButton15DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton15DialKeyPad

    private void jButton16DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton16DialKeyPad

    private void jButton17DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton17DialKeyPad

    private void jButton18DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton18DialKeyPad

    int LimitStart=0, LimitEnd=0;
    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        // TODO add your handling code here:
        Pnl_CaseHistory.removeAll();
        Pnl_Accused.removeAll();
        Pnl_CaseList.removeAll();
        Pnl_Caller.removeAll();
        String QueryPart = " Select Distinct(CaseID) from Consolidate where 1=1 ";
        Date dt = DtPck_Case.getDate();
        if (dt != null) {
            QueryPart += " AND DATEDIFF(DateStamp,'" + Global.JavaDateToMysql(dt) + "')=0 ";
        }
        if (CmbBx_CaseType.getSelectedItem().toString().trim().length() > 1) {
            QueryPart += " AND CaseType ='" + CmbBx_CaseType.getSelectedItem().toString() + "' ";
        }
        if (SrchFld_CmpltNo.getText().length() > 1) {
            QueryPart += " AND ReadableName ='" + SrchFld_CmpltNo.getText() + "' ";
        }

        String caselist = "(";
        try {
            Sql sql = new Sql();
            ResultSet rs = sql.ExecuteQuery(QueryPart);
            while (rs.next()) {
                if (caselist.length() > 2) {
                    caselist += ", '" + rs.getString(1) + "'";
                } else {
                    caselist += "'" + rs.getString(1) + "'";
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        caselist += ")";
        int CaseCount=0;
        if (caselist.length() > 3) {
            ArrayList<Cases> cases = new Cases().loadclass(" idCase IN " + caselist);
            for (Cases ob : cases) {
                CaseCount++;
                System.out.println("Adding Cases");
                Pnl_CaseElement obj = new Pnl_CaseElement();
                obj.LoadElement(ob);
                final String id = obj.id;
                obj.getBtn_Select().removeActionListener(obj.getBtn_Select().getActionListeners()[0]);
                obj.getBtn_Select().addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Caseid = Long.valueOf(id);
                        ArrayList<CaseHistory> caseHistory = new CaseHistory().loadclass(" CaseID =" + Caseid + " order by DateStamp DESC");
                        Pnl_Caller.removeAll();
                        Pnl_CaseHistory.removeAll();
                        for (CaseHistory ch : caseHistory) {
                            final String CaseHID = String.valueOf(ch.getId());
                            Pnl_CaseHistoryElement obj = new Pnl_CaseHistoryElement();
                            obj.LoadElement(ch);
                            obj.addMouseListener(new MouseListener() {
                                @Override
                                public void mouseClicked(MouseEvent e) {
                                    //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                }

                                @Override
                                public void mousePressed(MouseEvent e) {
                                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                }

                                @Override
                                public void mouseReleased(MouseEvent e) {
                                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                }

                                @Override
                                public void mouseEntered(MouseEvent ej) {
                                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                    Pnl_Caller.removeAll();
                                    Pnl_Caller.revalidate();
                                    Pnl_Caller.repaint();
                                    System.out.println("Got a mouse entered event");
                                    Caller e = new Caller().loadclass(" CallID=" + CaseHID).get(0);
                                    Pnl_CallerElement obj = new Pnl_CallerElement();
                                    obj.LoadElement(e);
                                    obj.remove(obj.getBtn_Select());
                                    obj.setSize(obj.preferredSize());
                                    obj.revalidate();
                                    Pnl_Caller.add(obj);
                                    Pnl_Caller.revalidate();
                                    Pnl_Caller.repaint();
                                }

                                @Override
                                public void mouseExited(MouseEvent e) {
                                    //     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                                }
                            });
                            Pnl_CaseHistory.add(obj);
                            Pnl_CaseHistory.revalidate();
                            Pnl_CaseHistory.repaint();
                        }
                        Pnl_Accused.removeAll();
                        ArrayList<Accused> ac = new Accused().loadclass(" Caseid=" + Caseid);
                        if (ac.size() > 0) {
                            String MSG = "";
                            MSG += " NAME :" + ac.get(0).getName() + "\n";
                            MSG += " Phone :" + ac.get(0).getPhone() + "\n";
                            MSG += " Address :" + ac.get(0).getAddress() + "\n";
                            MSG += " FIR: " + ac.get(0).getFir() + "\n";
                            //MSG += 
                            JTextArea ja = new JTextArea();
                            ja.setText(MSG);
                            ja.disable();
                            Pnl_Accused.add(ja);
                            Pnl_Accused.revalidate();
                            Pnl_Accused.repaint();
                        }
                    }
                });
                //System.out.println("<Case Details>" + ob.getPoliceStn() + "," + ob.getForward() + "," + ob.getStatus());
                // dscs.jPanel1.add(obj);
                //dsc.jScrollPane1.add(ob);
                Pnl_CaseList.add(obj);
                Pnl_CaseList.revalidate();
                Pnl_CaseList.repaint();
                this.repaint();
                System.out.println("Adding case element");
            }
             if (CaseCount==20){
            LimitStart+=20;
            LimitEnd+=20;
            Btn_More.setEnabled(true);
            }else{
                Btn_More.setEnabled(false);
            LimitStart=0;
            LimitEnd=20;
            }
    }//GEN-LAST:event_Btn_SearchActionPerformed
    }

    public static void setSelectedValue(JComboBox comboBox, String value) {

        String item;
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            item = (String) comboBox.getItemAt(i);
            if (item.equals(value)) {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }
    Long Caseid;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_CaseReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_CaseReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_CaseReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_CaseReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_CaseReports().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Dial;
    private javax.swing.JButton Btn_More;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JComboBox CmbBx_CaseType;
    private org.jdesktop.swingx.JXDatePicker DtPck_Case;
    private javax.swing.JPanel Pnl_Accused;
    private javax.swing.JPanel Pnl_Caller;
    private javax.swing.JPanel Pnl_CaseDirctry;
    private javax.swing.JPanel Pnl_CaseHistory;
    private javax.swing.JPanel Pnl_CaseList;
    public javax.swing.JPanel Pnl_RecrdDirctry;
    private org.jdesktop.swingx.JXSearchField SrchFld_CmpltNo;
    private javax.swing.JTextField TxtDialScreen;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    // End of variables declaration//GEN-END:variables
}
