/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DataBase.Tables.*;
import View.Dlg_AddTelephone;
import DataBase.OutBound;
import DataBase.Sql;
import DataBase.Tables.Accused;
import DataBase.Tables.Agent;
import DataBase.Tables.Caller;
import DataBase.Tables.Calls;
import DataBase.Tables.CaseHistory;
import DataBase.Tables.Cases;
import Layout.WrapLayout;
import View.Elements.Pnl_AccusedElement;
import View.Elements.Pnl_CallElement;
import View.Elements.Pnl_CallerElement;
import View.Elements.Pnl_CaseElement;
import View.Elements.Pnl_CaseHistoryElement;
import static View.Screen_CaseReports.infoBox;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author admin
 */
public class Screen_Managers extends javax.swing.JFrame {

    /**
     * Creates new form Screen_Supervisor
     */
        
    public Screen_Managers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Pnl_CaseList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pnl_CaseHistory = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pnl_Caller = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pnl_Accused = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SrchFld_CmpltNo = new org.jdesktop.swingx.JXSearchField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        CmbBx_CaseType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        DtPck_Case = new org.jdesktop.swingx.JXDatePicker();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        Pnl_RecrdDirctry = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        TxtDialScreen = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Btn_Dial = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        Pnl_CaseDirctry = new javax.swing.JPanel();
        Btn_Search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txt_PhoneNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout Pnl_CaseListLayout = new javax.swing.GroupLayout(Pnl_CaseList);
        Pnl_CaseList.setLayout(Pnl_CaseListLayout);
        Pnl_CaseListLayout.setHorizontalGroup(
            Pnl_CaseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        Pnl_CaseListLayout.setVerticalGroup(
            Pnl_CaseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Pnl_CaseList);
        Pnl_CaseList.setLayout(new WrapLayout());

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout Pnl_CaseHistoryLayout = new javax.swing.GroupLayout(Pnl_CaseHistory);
        Pnl_CaseHistory.setLayout(Pnl_CaseHistoryLayout);
        Pnl_CaseHistoryLayout.setHorizontalGroup(
            Pnl_CaseHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        Pnl_CaseHistoryLayout.setVerticalGroup(
            Pnl_CaseHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        Pnl_CaseHistory.setLayout(new WrapLayout());

        jScrollPane2.setViewportView(Pnl_CaseHistory);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Case List");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Case History");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Pnl_Caller.setBorder(javax.swing.BorderFactory.createTitledBorder("Caller Info"));

        javax.swing.GroupLayout Pnl_CallerLayout = new javax.swing.GroupLayout(Pnl_Caller);
        Pnl_Caller.setLayout(Pnl_CallerLayout);
        Pnl_CallerLayout.setHorizontalGroup(
            Pnl_CallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        Pnl_CallerLayout.setVerticalGroup(
            Pnl_CallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(Pnl_Caller);

        Pnl_Accused.setBorder(javax.swing.BorderFactory.createTitledBorder("Accused Info"));

        javax.swing.GroupLayout Pnl_AccusedLayout = new javax.swing.GroupLayout(Pnl_Accused);
        Pnl_Accused.setLayout(Pnl_AccusedLayout);
        Pnl_AccusedLayout.setHorizontalGroup(
            Pnl_AccusedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        Pnl_AccusedLayout.setVerticalGroup(
            Pnl_AccusedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(Pnl_Accused);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Case Info");

        jXLabel1.setText("Complaint No.");

        CmbBx_CaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Others", "Abduction", "Acid_Attack", "Callback_from_100", "Child_Sexual_Abuse (POSCO)", "Dangerous_Attack", "Domestic_Violence", "Dowry_Death", "Dowry_Violence", "Illegal_Confinement", "Incoming_obscene", "Kidnaping", "Life_Threatening_attack_by_Family", "Missing", "Murder", "Obscene_Call", "Petty_Quarrel", "Property_cases", "Rape", "Sexual_Abuse", "Stalking", "Threat_To_Life", "Violence_by_Khap_Biradari_Panchayat" }));

        jLabel6.setText("Case Type");

        jXLabel2.setText("Case Date");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane12.setPreferredSize(new java.awt.Dimension(1193, 120));

        Pnl_RecrdDirctry.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_RecrdDirctry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout Pnl_RecrdDirctryLayout = new javax.swing.GroupLayout(Pnl_RecrdDirctry);
        Pnl_RecrdDirctry.setLayout(Pnl_RecrdDirctryLayout);
        Pnl_RecrdDirctryLayout.setHorizontalGroup(
            Pnl_RecrdDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        Pnl_RecrdDirctryLayout.setVerticalGroup(
            Pnl_RecrdDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jScrollPane12.setViewportView(Pnl_RecrdDirctry);
        Pnl_RecrdDirctry.setLayout(new WrapLayout());

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 490, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));

        TxtDialScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDialScreenActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("1");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setIconTextGap(0);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4DialKeyPad(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("4");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(0);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5DialKeyPad(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("7");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(0);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6DialKeyPad(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("2");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(0);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7DialKeyPad(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("5");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setIconTextGap(0);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8DialKeyPad(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("8");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setIconTextGap(0);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9DialKeyPad(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton13.setText("3");
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setIconTextGap(0);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13DialKeyPad(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton14.setText("9");
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setIconTextGap(0);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14DialKeyPad(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton15.setText("6");
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setIconTextGap(0);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15DialKeyPad(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton16.setText("*");
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setIconTextGap(0);
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16DialKeyPad(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton17.setText("#");
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setIconTextGap(0);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17DialKeyPad(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton18.setText("0");
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setIconTextGap(0);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18DialKeyPad(evt);
            }
        });

        Btn_Dial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Dial.png"))); // NOI18N
        Btn_Dial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(Btn_Dial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDialScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Dial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDialScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 200, 140));

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane13.setPreferredSize(new java.awt.Dimension(1193, 120));

        Pnl_CaseDirctry.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_CaseDirctry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout Pnl_CaseDirctryLayout = new javax.swing.GroupLayout(Pnl_CaseDirctry);
        Pnl_CaseDirctry.setLayout(Pnl_CaseDirctryLayout);
        Pnl_CaseDirctryLayout.setHorizontalGroup(
            Pnl_CaseDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
        );
        Pnl_CaseDirctryLayout.setVerticalGroup(
            Pnl_CaseDirctryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane13.setViewportView(Pnl_CaseDirctry);
        Pnl_CaseDirctry.setLayout(new WrapLayout());

        jPanel1.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, -1));

        Btn_Search.setText("Search (Only Forwarded case)");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Phone Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SrchFld_CmpltNo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DtPck_Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3)
                        .addGap(333, 333, 333)
                        .addComponent(jLabel5)
                        .addGap(312, 312, 312)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SrchFld_CmpltNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(DtPck_Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDialScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDialScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDialScreenActionPerformed
    
    private void Btn_DialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DialActionPerformed
       Dlg_AddTelephone da = new Dlg_AddTelephone((Frame) this.getParent(), true);
       ArrayList<Telephone> tp = new ArrayList<>();
        da.getTxtPhone().setText(TxtDialScreen.getText());
        da.show();
        Telephone ph = new Telephone();
        ph.setNote(da.getTxtName().getText());
        try {
            ph.setNumber(Long.parseLong(da.getTxtPhone().getText()));
            tp.add(ph);
            ArrayList<CaseHistory> ch = new CaseHistory().loadclass(" CaseID ="+Caseid);
            for (Telephone obj : tp) {
                obj.setCaseHid(ch.get(0).getId());
                obj.savetodb();
            }
            infoBox("Number Successfully added", "Delhi Women Cell");
        } catch (Exception e) {
            e.printStackTrace();
            infoBox("You have entered invalid number", "Delhi Women Cell");
        }
        connect(TxtDialScreen.getText());
        
        /*
        caseentry.show();    }//GEN-LAST:event_Btn_DialActionPerformed
    */
    }

    public static void infoBox(String infoMessage, String location) {
        JOptionPane.showMessageDialog(null, infoMessage, location, JOptionPane.ERROR_MESSAGE);
    }
    private void jButton4DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton4DialKeyPad

    private void jButton5DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton5DialKeyPad

    private void jButton6DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton6DialKeyPad

    private void jButton7DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton7DialKeyPad

    private void jButton8DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton8DialKeyPad

    private void jButton9DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton9DialKeyPad

    private void jButton13DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton13DialKeyPad

    private void jButton14DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton14DialKeyPad

    private void jButton15DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton15DialKeyPad

    private void jButton16DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton16DialKeyPad

    private void jButton17DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton17DialKeyPad

    private void jButton18DialKeyPad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18DialKeyPad
        // TODO add your handling code here:
        TxtDialScreen.setText(TxtDialScreen.getText() + evt.getActionCommand());
    }//GEN-LAST:event_jButton18DialKeyPad
    public static void setSelectedValue(JComboBox comboBox, String value) {

        String item;
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            item = (String) comboBox.getItemAt(i);
            if (item.equals(value)) {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        // TODO add your handling code here:
        int Casecondition = 0;
        Pnl_CaseHistory.removeAll();
        Pnl_Accused.removeAll();
        Pnl_CaseList.removeAll();
        Pnl_Caller.removeAll();
        Pnl_CaseDirctry.removeAll();
        Pnl_RecrdDirctry.removeAll();
        String QueryPart = " Select Distinct(cs.CaseID) from Consolidate cs, forwardedcase fc where 1=1 and fc.CaseID= cs.CaseID";
        Date dt = DtPck_Case.getDate();
        if (dt != null) {
            QueryPart += " AND DATEDIFF(DateStamp,'" + Global.JavaDateToMysql(dt) + "')=0 ";
            Casecondition += 2;
        }
        if (CmbBx_CaseType.getSelectedItem().toString().trim().length() > 1) {
            QueryPart += " AND CaseType ='" + CmbBx_CaseType.getSelectedItem().toString() + "' ";
            Casecondition++;
        }
        if (SrchFld_CmpltNo.getText().length() > 1) {
            QueryPart += " AND ReadableName ='" + SrchFld_CmpltNo.getText() + "' ";
            Casecondition += 2;
        }
        if (Txt_PhoneNumber.getText().trim().length() > 1) {
            try {
                Long.parseLong(Txt_PhoneNumber.getText().trim());
                QueryPart += " AND Number Like '%" + Txt_PhoneNumber.getText().trim() + "%'";
                Casecondition += 2;
            } catch (Exception e) {
                infoBox("Please eneter a valid Phone number", "Delhi Women Cell");
            }
        }
        if (Casecondition < 2) {
            infoBox("Please specify atleast 2 search criteria", "Delhi Women Cell");
            return;
        }
//       QueryPart +=" Intersect Select CaseID from forwardedcase where Level='"+"S"+"'";
        String caselist = "(";
        try {
            Sql sql = new Sql();
            System.out.println(QueryPart);
            ResultSet rs = sql.ExecuteQuery(QueryPart);
            while (rs.next()) {
                if (caselist.length() > 2) {
                    caselist += ", '" + rs.getString(1) + "'";
                } else {
                    caselist += "'" + rs.getString(1) + "'";
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        caselist += ")";
        if (caselist.length() > 3) {
            ArrayList<Cases> cases = new Cases().loadclass(" idCase IN " + caselist);
            for (Cases ob : cases) {
                System.out.println("Adding Cases");
                Pnl_CaseElement obj = new Pnl_CaseElement();
                obj.LoadElement(ob);
                final String id = obj.id;
                obj.getBtn_Select().removeActionListener(obj.getBtn_Select().getActionListeners()[0]);
                obj.getBtn_Select().addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Caseid = Long.valueOf(id);
                        ArrayList<CaseHistory> caseHistory = new CaseHistory().loadclass(" CaseID =" + Caseid + " order by DateStamp DESC");
                        Pnl_Caller.removeAll();
                        Pnl_CaseHistory.removeAll();
                        Pnl_CaseDirctry.removeAll();
                        Pnl_RecrdDirctry.removeAll();
                        Pnl_Accused.removeAll();
                        ArrayList<Accused> ac = new Accused().loadclass(" Caseid=" + Caseid);
                        ArrayList<Legal> le = new Legal().loadclass(" CaseID=" + Caseid);
                        ArrayList<Caller> ca = new Caller().loadclass("CallID in (select idCase_History from case_history where CaseID =" + Caseid + " ) order by idCaller DESC");
                        /*System.out.println("starts here");
                         String MSG = "";
                         if (ac.size() > 0) {
                         MSG += " NAME :" + ac.get(0).getName() + "\n";
                         MSG += " Phone :" + ac.get(0).getPhone() + "\n";
                         MSG += " Address :" + ac.get(0).getAddress() + "\n";
                         }
                         if (le.size() > 0) {
                         MSG += " DD: " + le.get(0).getDD() + "\n";
                         MSG += " Fir: " + le.get(0).getFir() + "\n";
                         MSG += " Challan: " + le.get(0).getChallan() + "\n";
                         MSG += " Judgement: " + le.get(0).getJudgement() + "\n";
                         //MSG += 
                         System.out.println(MSG);
                         }
                         System.out.println(MSG);
                         if (MSG.length() != 0) {
                         JTextArea ja = new JTextArea();
                         ja.setText(MSG);
                         ja.setSize(ja.getPreferredSize());
                         ja.setBackground(Color.yellow);
                         ja.revalidate();
                         ja.repaint();

                         //ja.disable();
                         Pnl_Accused.removeAll();
                         Pnl_Accused.add(ja);
                         }

                         //  Pnl_Accused.revalidate();
                         //    Pnl_Accused.repaint();
                         System.out.println("start");
                         //  return;
                         Pnl_Accused.revalidate();
                         Pnl_Accused.repaint();
                         Pnl_Caller.removeAll();*/
                        Pnl_CallerElement ce = new Pnl_CallerElement();
                        System.out.println("Adding Caller element");
                        try {
                            if (ca.size() > 0) {
                                ce.LoadElement(ca.get(0));
                            } else {
                                infoBox("No caller information available.", "Delhi Women Cell");
                            }
                        } catch (Exception ex) {
                            System.err.println("Caller panel error" + ex);
                        }
                        ce.getBtn_Select().disable();
                        ce.remove(ce.getBtn_Select());
                        ce.setSize(ce.preferredSize());
                        Pnl_Caller.add(ce);
                        Pnl_Caller.revalidate();
                        Pnl_Caller.repaint();

                        Pnl_AccusedElement pae = new Pnl_AccusedElement();
                        try {
                            if (ac.size() > 0) {
                                pae.LoadElement_Accused(ac.get(0));
                            }
                            if (le.size() > 0) {
                                pae.LoadElement_Legal(le.get(0));
                            }
                        } catch (Exception ex) {
                            System.err.println("accused panel error" + ex);
                        }
                        pae.EnableSave(Caseid);
                        pae.setSize(291, 291);
                        Pnl_Accused.add(pae);
                        Pnl_Accused.revalidate();
                        Pnl_Accused.repaint();
                        System.out.println("in accuse panel printing block");
                        for (CaseHistory ch : caseHistory) {
                            final String CaseHID = String.valueOf(ch.getId());
                            Pnl_CaseHistoryElement obj = new Pnl_CaseHistoryElement();
                            obj.LoadElement(ch);
                            /*obj.addMouseListener(new MouseListener() {
                             @Override
                             public void mouseClicked(MouseEvent e) {
                             //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                             }

                             @Override
                             public void mousePressed(MouseEvent e) {
                             //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                             }

                             @Override
                             public void mouseReleased(MouseEvent e) {
                             //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                             }

                             @Override
                             public void mouseEntered(MouseEvent ej) {
                             //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                             Pnl_Caller.removeAll();
                             System.out.println("Got a mouse entered event");
                             try {
                             Caller e = new Caller().loadclass(" CallID=" + CaseHID).get(0);
                             Pnl_CallerElement obj = new Pnl_CallerElement();
                             //String Callerid = new Calls().loadclass(" CaseHID="+e.getCallid()).get(0).getNumber();
                             //obj.setToolTipText("Call From :"+ Callerid);
                             obj.LoadElement(e);
                             obj.remove(obj.getBtn_Select());
                             obj.setSize(obj.preferredSize());
                             Pnl_Caller.add(obj);
                             Pnl_Caller.revalidate();
                             Pnl_Caller.repaint();
                             } catch (Exception e) {
                             e.printStackTrace();
                             }
                             }

                             @Override
                             public void mouseExited(MouseEvent e) {
                             //     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                             }
                             });*/
                            Pnl_CaseHistory.add(obj);
                            Pnl_CaseHistory.revalidate();
                            Pnl_CaseHistory.repaint();
                        }
                        /*Pnl_Accused.removeAll();
                         ArrayList<Accused> ac = new Accused().loadclass(" Caseid=" + Caseid);
                         Pnl_Accused.removeAll();
                         if (ac.size() > 0) {
                         String MSG = "";
                         MSG += " NAME :" + ac.get(0).getName() + "\n";
                         MSG += " Phone :" + ac.get(0).getPhone() + "\n";
                         MSG += " Address :" + ac.get(0).getAddress() + "\n";
                         MSG += " FIR: " + ac.get(0).getFir() + "\n";
                         //MSG += 
                         if (MSG.length() != 0) {
                         JTextArea ja = new JTextArea();
                         ja.setText(MSG);
                         ja.setSize(ja.getPreferredSize());
                         ja.setBackground(Color.yellow);
                         ja.revalidate();
                         ja.repaint();

                         //ja.disable();
                         Pnl_Accused.removeAll();
                         Pnl_Accused.add(ja);
                         }
                         }
                         Pnl_Accused.revalidate();
                         Pnl_Accused.repaint();*/

                        ArrayList<DataBase.Tables.Directory> dir1 = new DataBase.Tables.Directory().loadclass(" AREA like (select PoliceStation from `case` where idCase = " + Caseid + ")");
                        ArrayList<DataBase.Tables.Telephone> tl1 = new DataBase.Tables.Telephone().loadclass("CaseHID in (select idCase_HIstory from case_history where CaseID = " + Caseid + ")");
                        for (DataBase.Tables.Directory dir : dir1) {

                            Pnl_CallElement pce = new Pnl_CallElement();
                            pce.LoadElement(dir);
                            final String number = dir.getNumber();
                            pce.getBtn_CallElement_Dial().removeActionListener(pce.getBtn_CallElement_Dial().getActionListeners()[0]);
                            pce.getBtn_CallElement_Dial().addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    connect(number);
                                }
                            });
                            Pnl_CaseDirctry.add(pce);
                            System.out.println("Added a Case directory element");
                        }
                        for (DataBase.Tables.Telephone tl : tl1) {
                            Pnl_CallElement pce = new Pnl_CallElement();
                            pce.Lbl_CallElement_number.setText(String.valueOf(tl.getNumber()));
                            pce.Lbl_CallElement_Name.setText(tl.getNote());
                            final String number = String.valueOf(tl.getNumber());
                            pce.getBtn_CallElement_Dial().removeActionListener(pce.getBtn_CallElement_Dial().getActionListeners()[0]);
                            pce.getBtn_CallElement_Dial().addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    connect(number);
                                }
                            });
                            Pnl_RecrdDirctry.add(pce);
                            System.out.println("Added a Record directory element");
                        }
                        Pnl_CaseDirctry.revalidate();

                        Pnl_CaseDirctry.repaint();

                        Pnl_RecrdDirctry.revalidate();

                        Pnl_RecrdDirctry.repaint();
                    }
                });
                //System.out.println("<Case Details>" + ob.getPoliceStn() + "," + ob.getForward() + "," + ob.getStatus());
                // dscs.jPanel1.add(obj);
                //dsc.jScrollPane1.add(ob);
                Pnl_CaseList.add(obj);

                Pnl_CaseList.revalidate();

                Pnl_CaseList.repaint();

                this.repaint();

                System.out.println(
                        "Adding case element");
            }
    }//GEN-LAST:event_Btn_SearchActionPerformed
    }
    Long Caseid;

    /**
     * @param args the command line arguments
     */
    public void connect(String number) {

        if (Caseid == null) {
            infoBox("Please select a Case before you proceed", "Delhi Women Cell");
            return;
        }
        if (Caseid > 0) {
            try {
                Cases cs = new Cases().loadclass(" idCase=" + Caseid).get(0);
                String CaseName = cs.getReadableName();
                infoBox("You are going to work on case : " + CaseName, "Delhi Women Cell");
            } catch (Exception ex) {
                infoBox("Please select a Case before you proceed", "Delhi Women Cell");
                return;
            }
        }
        final OutBound ob = new OutBound();
        ob.connect(number);
        System.out.println("number to connect" + number);
        infoBox("Your Call Request is submitted. Please wait for 1 minute for server to connect you.", "Delhi WomenCell");
        final Pnl_CaseHistoryElement pce = new Pnl_CaseHistoryElement();
        pce.AudioPanel.disable();
        pce.getBtn_Save().setEnabled(true);
        pce.getBtn_Save().removeActionListener(pce.getBtn_Save().getActionListeners()[0]);
        pce.getBtn_Save().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                /* action to be performed on save buttn to save the history*/
                try {
                    pce.savedb();
                    System.out.println(pce.getElement().getId());

                    Calls cl = new Calls().loadclass("Bound='OUT' and CallUUID=" + ob.confname).get(0);
                    cl.setCaseHID(pce.getElement().getId());

                    cl.setAgentId(Integer.parseInt(Global.AgentID));
                    cl.updatedb();
                    dispose();
                } catch (Exception exc) {
                    exc.printStackTrace();
                    infoBox("Please try again!", "Delhi WomenCell");
                }
            }
        });
        pce.getTxt_Note().setEnabled(true);
        pce.getTxt_Advice().setEnabled(true);
        pce.Agentid = Long.valueOf(Global.AgentPK);
        pce.Caseid = Caseid;
        JDialog caseentry = new JDialog(this);
        caseentry.add(pce);
        caseentry.getContentPane().setSize(caseentry.getContentPane().getPreferredSize());
        caseentry.setSize(caseentry.getPreferredSize());
        caseentry.setSize(caseentry.getSize().width, caseentry.getSize().height + 25);
        caseentry.revalidate();
        caseentry.repaint();
        caseentry.show();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_Managers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_Managers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_Managers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_Managers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_Managers().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Dial;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JComboBox CmbBx_CaseType;
    private org.jdesktop.swingx.JXDatePicker DtPck_Case;
    private javax.swing.JPanel Pnl_Accused;
    private javax.swing.JPanel Pnl_Caller;
    public javax.swing.JPanel Pnl_CaseDirctry;
    private javax.swing.JPanel Pnl_CaseHistory;
    private javax.swing.JPanel Pnl_CaseList;
    public javax.swing.JPanel Pnl_RecrdDirctry;
    private org.jdesktop.swingx.JXSearchField SrchFld_CmpltNo;
    private javax.swing.JTextField TxtDialScreen;
    private javax.swing.JTextField Txt_PhoneNumber;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    // End of variables declaration//GEN-END:variables
}
