/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Elements;

import DataBase.Tables.Agent;
import DataBase.Tables.Audio;
import DataBase.Tables.Calls;
import DataBase.Tables.CaseHistory;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import Layout.WrapLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author admin
 */
public class Pnl_CaseHistoryElement extends javax.swing.JPanel {

    public Long CaseHisoryID;
    public Long Caseid;
    public Long Agentid;

    public JComboBox getCmbBx_Reffered() {
        return CmbBx_Reffered;
    }

    public void setCmbBx_Reffered(JComboBox CmbBx_Reffered) {
        this.CmbBx_Reffered = CmbBx_Reffered;
    }

    public void setCaseHisoryID(Long CaseHisoryID) {
        this.CaseHisoryID = CaseHisoryID;
    }

    public JLabel getLbl_Agent() {
        return Lbl_Agent;
    }

    public JLabel getLbl_CallerID() {
        return Lbl_CallerID;
    }

    public void setLbl_CallerID(JLabel Lbl_CallerID) {
        this.Lbl_CallerID = Lbl_CallerID;
    }

    public void setLbl_Agent(JLabel Lbl_Agent) {
        this.Lbl_Agent = Lbl_Agent;
    }

    public JLabel getLbl_DateTime() {
        return Lbl_DateTime;
    }

    public void setLbl_DateTime(JLabel Lbl_DateTime) {
        this.Lbl_DateTime = Lbl_DateTime;
    }

    public JTextArea getTxt_Advice() {
        return Txt_Advice;
    }

    public void setTxt_Advice(JTextArea Txt_Advice) {
        this.Txt_Advice = Txt_Advice;
    }

    public JTextArea getTxt_Note() {
        return Txt_Note;
    }

    public void setTxt_Note(JTextArea Txt_Note) {
        this.Txt_Note = Txt_Note;
    }

    public JTextField getTxt_Reffered() {
        return Txt_Reffered;
    }

    public void setTxt_Reffered(JTextField Txt_Reffered) {
        this.Txt_Reffered = Txt_Reffered;
    }

    /**
     * Creates new form Pnl_CaseHistoryElement
     */
    public Pnl_CaseHistoryElement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Audio = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        AudioPanel = new javax.swing.JPanel();
        Lbl_DateTime = new javax.swing.JLabel();
        Lbl_Agent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_Note = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Reffered = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Lbl_CallerID = new javax.swing.JLabel();
        Btn_Save = new javax.swing.JButton();
        CmbBx_Reffered = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        Txt_Advice = new javax.swing.JTextArea();

        Dlg_Audio.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout AudioPanelLayout = new javax.swing.GroupLayout(AudioPanel);
        AudioPanel.setLayout(AudioPanelLayout);
        AudioPanelLayout.setHorizontalGroup(
            AudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        AudioPanelLayout.setVerticalGroup(
            AudioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        AudioPanel.setLayout(new WrapLayout());

        jScrollPane2.setViewportView(AudioPanel);

        javax.swing.GroupLayout Dlg_AudioLayout = new javax.swing.GroupLayout(Dlg_Audio.getContentPane());
        Dlg_Audio.getContentPane().setLayout(Dlg_AudioLayout);
        Dlg_AudioLayout.setHorizontalGroup(
            Dlg_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        Dlg_AudioLayout.setVerticalGroup(
            Dlg_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        Lbl_DateTime.setText("DD/MM/YY HH:MM:SS");

        Lbl_Agent.setText("AgentName");

        jLabel1.setText("Note");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Txt_Note.setColumns(20);
        Txt_Note.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Txt_Note.setLineWrap(true);
        Txt_Note.setRows(5);
        Txt_Note.setWrapStyleWord(true);
        Txt_Note.setAutoscrolls(false);
        Txt_Note.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt_Note.setEnabled(false);
        jScrollPane1.setViewportView(Txt_Note);

        jLabel2.setText("Advice");

        jLabel3.setText("Reffered");

        Txt_Reffered.setForeground(new java.awt.Color(226, 0, 0));
        Txt_Reffered.setEnabled(false);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/mp3.png"))); // NOI18N
        jButton2.setText("Audio");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Lbl_CallerID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_CallerID.setForeground(new java.awt.Color(0, 51, 255));
        Lbl_CallerID.setText("CallerID :");

        Btn_Save.setText("Save");
        Btn_Save.setEnabled(false);
        Btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SaveActionPerformed(evt);
            }
        });

        CmbBx_Reffered.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Other", "100", "1096", "SHO PS", "DCP/ACP", "DLSA", "DCW", "Mahila Panchayat", "Shelter Home", "Protection Ofiicer", "Child Welfare Comitee", "GRC", "Awaaj Uthao", "IHBAS", "DTC", "NGO", "Hospital", "Ambulance" }));
        CmbBx_Reffered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBx_RefferedActionPerformed(evt);
            }
        });

        jScrollPane3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Txt_Advice.setColumns(20);
        Txt_Advice.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Txt_Advice.setLineWrap(true);
        Txt_Advice.setRows(5);
        Txt_Advice.setWrapStyleWord(true);
        Txt_Advice.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt_Advice.setEnabled(false);
        jScrollPane3.setViewportView(Txt_Advice);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(Txt_Reffered, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(CmbBx_Reffered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Lbl_DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Btn_Save)
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Agent, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_CallerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Agent)
                    .addComponent(Lbl_CallerID))
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Reffered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Save)
                    .addComponent(CmbBx_Reffered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void savedb() {
        CaseHistory ch = new CaseHistory();
        ch.setAdvice(Txt_Advice.getText());
        ch.setAgentID(Agentid);
        ch.setCaseID(Caseid);
        ch.setNote(Txt_Note.getText());
        ch.setReffered(CmbBx_Reffered.getSelectedItem().toString());
        ch.savetodb();
        element = ch;
    }

    public void LoadElement(CaseHistory ch) {
        Pnl_CaseHistoryElement obj = this;
        obj.setCaseHisoryID(ch.getId());
        obj.getLbl_DateTime().setText("Case Status on " + ch.getDatestamp());
        obj.getLbl_DateTime().setSize(obj.getLbl_DateTime().getPreferredSize());
        Agent ag = new Agent().loadclass(" idAgent=" + ch.getAgentID()).get(0);
        obj.getLbl_Agent().setText("Case Handled by " + ag.getNAME());
        obj.getLbl_Agent().setSize(obj.getLbl_Agent().getPreferredSize());
        obj.getTxt_Advice().setText(ch.getAdvice());
        obj.getTxt_Note().setText(ch.getNote());
        obj.getTxt_Reffered().setText(ch.getReffered());
        setSelectedValue(obj.getCmbBx_Reffered(), ch.getReffered());
        String Callerid = "";
        try {
            Callerid = new Calls().loadclass(" CaseHID=" + ch.getId()).get(0).getNumber();
        } catch (Exception ex) {
            Callerid = "OutBound Call";
        }
        obj.getLbl_CallerID().setText("Call From : " + Callerid);
    element = ch;
    }
    CaseHistory element;
public CaseHistory getElement(){

    return element;
}
    public static void setSelectedValue(JComboBox comboBox, String value) {
        String item;
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            item = (String) comboBox.getItemAt(i);
            if (item.equals(value)) {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<Calls> cl = new Calls().loadclass(" CaseHID =" + CaseHisoryID);
        for (Calls c : cl) {
            ArrayList<Audio> au = new Audio().loadclass(" Callid =" + c.getId());
            for (Audio a : au) {

                Pnl_AudioElement pa = new Pnl_AudioElement();
                pa.setAudioFile(a.getFilepath());
                pa.getLbl_CallDescription().setText(a.getNumber());
                AudioPanel.add(pa);
                AudioPanel.setSize(AudioPanel.getPreferredSize());
            }
        }


        Dlg_Audio.setSize(Dlg_Audio.getPreferredSize());
        Dlg_Audio.show();
        Dlg_Audio.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                AudioPanel.removeAll();
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    public JButton getBtn_Save() {
        return Btn_Save;
    }

    public void setBtn_Save(JButton Btn_Save) {
        this.Btn_Save = Btn_Save;
    }

    private void Btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SaveActionPerformed
        // TODO add your handling code here:
        savedb();
    }//GEN-LAST:event_Btn_SaveActionPerformed

    private void CmbBx_RefferedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBx_RefferedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbBx_RefferedActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AudioPanel;
    private javax.swing.JButton Btn_Save;
    private javax.swing.JComboBox CmbBx_Reffered;
    public javax.swing.JDialog Dlg_Audio;
    private javax.swing.JLabel Lbl_Agent;
    private javax.swing.JLabel Lbl_CallerID;
    private javax.swing.JLabel Lbl_DateTime;
    private javax.swing.JTextArea Txt_Advice;
    private javax.swing.JTextArea Txt_Note;
    private javax.swing.JTextField Txt_Reffered;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
