/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Elements;

import DataBase.Tables.*;
import View.Dlg_AddTelephone;
import View.Dlg_SelectCaller;
import View.Dlg_SelectCase;
import View.Global;
import java.awt.Color;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class Pnl_CaseElement extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_CaseElement
     */
    public ArrayList<Telephone> tp = new ArrayList<>();
    public String id;

    public Pnl_CaseElement() {
        initComponents();
    }

    public JTextField getTxt_Forward() {
        return Txt_Forward;
    }

    public void setTxt_Forward(JTextField Txt_Forward) {
        this.Txt_Forward = Txt_Forward;
    }

    public JComboBox getCmbBx_Status() {
        return CmbBx_Status;
    }

    public void setCmbBx_Status(JComboBox CmbBx_Status) {
        this.CmbBx_Status = CmbBx_Status;
    }

    public JTextField getTxt_PoliceStn() {
        return Txt_PoliceStn;
    }

    public void setTxt_PoliceStn(JTextField Txt_PoliceStn) {
        this.Txt_PoliceStn = Txt_PoliceStn;
    }

    public JTextField getTxt_FamiliarName() {
        return Txt_FamiliarName;
    }

    public void setTxt_FamiliarName(JTextField jTextField1) {
        this.Txt_FamiliarName = jTextField1;
    }

    public JComboBox getCmbBx_CaseType() {
        return CmbBx_CaseType;
    }

    public void setCmbBx_CaseType(JComboBox CmbBx_CaseType) {
        this.CmbBx_CaseType = CmbBx_CaseType;
    }

    public static void setSelectedValue(JComboBox comboBox, String value) {

        String item;
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            item = (String) comboBox.getItemAt(i);
            if (item.equals(value)) {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_Select = new javax.swing.JButton();
        Txt_PoliceStn = new javax.swing.JTextField();
        Txt_Forward = new javax.swing.JTextField();
        Txt_FamiliarName = new javax.swing.JTextField();
        Btn_Save = new javax.swing.JButton();
        CmbBx_CaseType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        CmbBx_Status = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        setPreferredSize(new java.awt.Dimension(310, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Police Station");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Status");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Forward");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Complaint No");

        Btn_Select.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_Select.setText("Select");
        Btn_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SelectActionPerformed(evt);
            }
        });

        Txt_PoliceStn.setText("jTextField1");

        Txt_FamiliarName.setText("jTextField1");
        Txt_FamiliarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_FamiliarNameActionPerformed(evt);
            }
        });

        Btn_Save.setText("Save");
        Btn_Save.setEnabled(false);
        Btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SaveActionPerformed(evt);
            }
        });

        CmbBx_CaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Others", "Abduction", "Acid_Attack", "Callback_from_100", "Child_Sexual_Abuse (POSCO)", "Dangerous_Attack", "Domestic_Violence", "Dowry_Death", "Dowry_Violence", "Illegal_Confinement", "Incoming_obscene", "Kidnaping", "Life_Threatening_attack_by_Family", "Missing", "Murder", "Obscene_Call", "Petty_Quarrel", "Property_cases", "Rape", "Sexual_Abuse", "Stalking", "Threat_To_Life", "Violence_by_Khap_Biradari_Panchayat" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Case Type");

        CmbBx_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primary intervention done", "Case in progress", "Case closed" }));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Add.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_PoliceStn)
                                    .addComponent(Txt_Forward, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbBx_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_Select)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Txt_FamiliarName))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(Btn_Save)
                                .addGap(33, 33, 33)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_PoliceStn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CmbBx_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Forward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Txt_FamiliarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmbBx_CaseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_Save)
                        .addComponent(Btn_Select))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_FamiliarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_FamiliarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_FamiliarNameActionPerformed

    public JButton getBtn_Select() {
        return Btn_Select;
    }

    public void setBtn_Select(JButton Btn_Select) {
        this.Btn_Select = Btn_Select;
    }

    public void LoadElement(Cases ob) {
        this.getTxt_PoliceStn().setText(ob.getPoliceStn());
        this.getTxt_Forward().setText(ob.getForward());
        setSelectedValue(this.getCmbBx_CaseType(), ob.getCaseType());
        System.out.println("Setting Case TYpe = " + ob.getCaseType());
        setSelectedValue(this.getCmbBx_Status(), ob.getStatus());
        this.getTxt_FamiliarName().setText(ob.getReadableName());
        this.id = String.valueOf(ob.getId());
        if (Global.AgentLevel.equals("supervisor")) {
            this.Btn_Save.setEnabled(true);
        }
        if(ob.getReadableName().toLowerCase().startsWith("blank") || ob.getReadableName().toLowerCase().startsWith("men")||ob.getReadableName().toLowerCase().startsWith("advice")){
        this.setBackground(Color.red);
        }
        this.repaint();
    }
    private void Btn_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SelectActionPerformed
        // TODO add your handling code here:
        Dlg_SelectCase dc = (Dlg_SelectCase) this.getRootPane().getParent();
        dc.PoliceStn = this.Txt_PoliceStn.getText();
        dc.Forward = this.Txt_Forward.getText();
        dc.Status = this.CmbBx_Status.getSelectedItem().toString();
        dc.ReadableName = this.Txt_FamiliarName.getText();
        dc.id = this.id;
        dc.CaseType = this.CmbBx_CaseType.getSelectedItem().toString();
        dc.setVisible(false);
        //  System.out.println("Original:"+this.Txt_CallerAddress.getText()+","+this.Txt_CallerAge.getText()+",");
        //  System.out.println(this.CaseHID.toString());
        //  System.out.println("Copied:"+dc.Address+","+dc.Age+","+dc.CaseHID.toString());
    }//GEN-LAST:event_Btn_SelectActionPerformed

    private void Btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SaveActionPerformed
        // TODO add your handling code here:
        Cases cs = new Cases();
        cs.setId(Long.valueOf(this.id));
        cs.setCaseType(CmbBx_CaseType.getSelectedItem().toString());
        cs.setPoliceStn(Txt_PoliceStn.getText());
        cs.setForward(Txt_Forward.getText());
        cs.setReadableName(Txt_FamiliarName.getText());
        cs.setStatus(this.CmbBx_Status.getSelectedItem().toString());
        cs.updatedb();
        infoBox("Case Information Updated!!", "Delhi Women Cell");
    }//GEN-LAST:event_Btn_SaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dlg_AddTelephone da = new Dlg_AddTelephone((Frame) this.getParent().getParent().getParent().getParent().getParent().getParent().getParent(), true);
        da.show();
        Telephone ph = new Telephone();
        ph.setNote(da.getTxtName().getText());
        System.out.println("name"+da.getTxtName().getText());
        System.out.println("number"+da.getTxtPhone().getText());
        try {
            ph.setNumber(Long.parseLong(da.getTxtPhone().getText()));
            tp.add(ph);
            ArrayList<CaseHistory> ch = new CaseHistory().loadclass(" CaseID ="+Long.parseLong(this.id));
            for (Telephone ob : tp) {
                ob.setCaseHid(ch.get(0).getId());
                ob.savetodb();
            }
            infoBox("Number Successfully added", "Delhi Women Cell");

        } catch (Exception e) {
            e.printStackTrace();
            infoBox("You have entered invalid number", "Delhi Women Cell");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public static void infoBox(String infoMessage, String location) {
        JOptionPane.showMessageDialog(null, infoMessage, location, JOptionPane.ERROR_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Save;
    private javax.swing.JButton Btn_Select;
    private javax.swing.JComboBox CmbBx_CaseType;
    private javax.swing.JComboBox CmbBx_Status;
    private javax.swing.JTextField Txt_FamiliarName;
    private javax.swing.JTextField Txt_Forward;
    private javax.swing.JTextField Txt_PoliceStn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
