/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Elements;

import DataBase.Sql;
import View.Global;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Pnl_CallElement extends javax.swing.JPanel {

    /**
     * Creates new form xyz
     */
    public String id;
    public Pnl_CallElement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_CallElement_Name = new javax.swing.JLabel();
        Lbl_CallElement_number = new javax.swing.JLabel();
        Btn_CallElement_Dial = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_CallElement_Name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Lbl_CallElement_Name.setText("Sho Xyz Singh");

        Lbl_CallElement_number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Lbl_CallElement_number.setText("9087654321");

        Btn_CallElement_Dial.setText("Dial");
        Btn_CallElement_Dial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CallElement_DialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Lbl_CallElement_Name)
                .addGap(68, 68, 68)
                .addComponent(Lbl_CallElement_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Btn_CallElement_Dial))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Lbl_CallElement_Name)
                .addComponent(Lbl_CallElement_number)
                .addComponent(Btn_CallElement_Dial))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CallElement_DialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CallElement_DialActionPerformed
        // TODO add your handling code here:
//"In a queue call"" thenn uuid for call
        String Query = "Select state from agents where name='" + Global.AgentID + "'";
        Sql sql = new Sql();
        ResultSet rs;
        rs = sql.ExecuteQuery(Query);
        try {
            if (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase("In a queue call")) {
                    long confname = new Date().getTime() / 100;
                    Query = "Select CallUUID from call_scheduling where AgentID='" + Global.AgentID + "'";
                    ResultSet rst = sql.ExecuteQuery(Query);
                    if (rst.next()) {
                        String CallUUID = rst.getString(1);
                        Query = "Insert into Outbound(OutType, OutName, Number, NumberType, Status, Schedule)";
                        Query += " value('conf','" + confname + "','" + Lbl_CallElement_number.getText() + "','GSM','0',NOW())";
                        sql.ExecuteUpdate(Query);
                        Query = "Insert into Outbound(OutType, OutName, Number, NumberType, Status, Schedule)";
                        Query += " value('conf','" + confname + "','" + CallUUID + "','UUID','0',NOW())";
                        sql.ExecuteUpdate(Query);
                    } else {
                        infoBox("Something wrong with making the call", "Delhi Women Cell");

                    }
                } else {
                    if (false) {
                        long confname = new Date().getTime() / 100;
                        Query = "Insert into Outbound(OutType, OutName, Number, NumberType, Status, Schedule)";
                        Query += " value('conf','" + confname + "','" + Lbl_CallElement_number.getText() + "','GSM','0',NOW())";
                        sql.ExecuteUpdate(Query);
                    } else {
                        infoBox("Currently can not make call", "Delhi Women Cell");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_CallElement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_CallElement_DialActionPerformed
    public void LoadElement(DataBase.Tables.Directory ob) {
        this.Lbl_CallElement_Name.setText(ob.getInfo()+" "+ob.getService());
        this.Lbl_CallElement_number.setText(ob.getNumber());
        System.out.println("number"+ob.getNumber());
        System.out.println("infor"+ob.getInfo());
        this.id = String.valueOf(ob.getId());        
        this.repaint();
    }

    public static void infoBox(String infoMessage, String location) {
        JOptionPane.showMessageDialog(null, infoMessage, location, JOptionPane.INFORMATION_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_CallElement_Dial;
    public javax.swing.JLabel Lbl_CallElement_Name;
    public javax.swing.JLabel Lbl_CallElement_number;
    // End of variables declaration//GEN-END:variables
}
