/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Elements;

import DataBase.Sql;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import temp.Design;

/**
 *
 * @author admin
 */
public class Pnl_AudioElement extends javax.swing.JPanel {
Player mp3player = null;
String AudioFile="";

    public String getAudioFile() {
        return AudioFile;
    }

    public void setAudioFile(String AudioFile) {
        this.AudioFile = AudioFile;
    }

    /**
     * Creates new form Pnl_Audio
     */
    public Pnl_AudioElement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Play = new javax.swing.JButton();
        Btn_Stop = new javax.swing.JButton();
        Lbl_CallDescription = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));

        Btn_Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/mp3.png"))); // NOI18N
        Btn_Play.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PlayActionPerformed(evt);
            }
        });

        Btn_Stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/download.jpg"))); // NOI18N
        Btn_Stop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Lbl_CallDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Btn_Play, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn_Play, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
            .addComponent(Btn_Stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Lbl_CallDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PlayActionPerformed
        // TODO add your handling code here:
        playfile pf = new playfile();
        Thread evenThread = new Thread(pf, "evenThread");
        evenThread.start();

    }//GEN-LAST:event_Btn_PlayActionPerformed

    public JLabel getLbl_CallDescription() {
        return Lbl_CallDescription;
    }

    public void setLbl_CallDescription(JLabel Lbl_CallDescription) {
        this.Lbl_CallDescription = Lbl_CallDescription;
    }

    private void Btn_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StopActionPerformed
        // TODO add your handling code here:
        mp3player.close();
    }//GEN-LAST:event_Btn_StopActionPerformed
class playfile implements Runnable{
  
    public playfile() {
        
    }
            @Override
            public void run() {
      try {
          play();
      } catch (JavaLayerException ex) {
          Logger.getLogger(Design.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
          Logger.getLogger(Design.class.getName()).log(Level.SEVERE, null, ex);
      }
            }
public void play() throws JavaLayerException, IOException {
//        String song = "http://sound17.mp3pk.com/indian/bhaagmilkhabhaag/[Songs.PK]%20Bhaag%20Milkha%20Bhaag%20-%2001%20-%20Gurbani.mp3";
       // String fileurl=ServerUrl+Credential+jLabel1.getText();
        //String fileurl="http://192.168.16.176/download.php?file=1.mp3";
        String fileurl = "http://"+Sql.Server_IP+"/download.php?file="+AudioFile;
        BufferedInputStream in = null;
        try {
          in = new BufferedInputStream(new URL(fileurl).openStream());
          mp3player = new Player(in);
          mp3player.play();
        } catch (MalformedURLException ex) {
        } catch (IOException e) {
        } catch (JavaLayerException e) {
        } catch (NullPointerException ex) {
        }
        
}

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Play;
    private javax.swing.JButton Btn_Stop;
    private javax.swing.JLabel Lbl_CallDescription;
    // End of variables declaration//GEN-END:variables
}
